# coding: utf-8

"""
    OOXML Automation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0-no-tags
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import presalytics_ooxml_automation
from presalytics_ooxml_automation.api.default_api import DefaultApi  # noqa: E501
from presalytics_ooxml_automation.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = presalytics_ooxml_automation.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_chart_axes_get_id(self):
        """Test case for chart_axes_get_id

        Axes: Get by Id  # noqa: E501
        """
        pass

    def test_chart_axis_data_types_get(self):
        """Test case for chart_axis_data_types_get

        AxisDataTypes: List All Possible Types  # noqa: E501
        """
        pass

    def test_chart_axis_data_types_get_id(self):
        """Test case for chart_axis_data_types_get_id

        AxisDataTypes: Get by Id  # noqa: E501
        """
        pass

    def test_chart_chart_data_get_id(self):
        """Test case for chart_chart_data_get_id

        ChartData: Get by Id  # noqa: E501
        """
        pass

    def test_chart_column_collections_get_id(self):
        """Test case for chart_column_collections_get_id

        ColumnCollections: Get by Id  # noqa: E501
        """
        pass

    def test_chart_columns_get_id(self):
        """Test case for chart_columns_get_id

        Columns: Get by Id  # noqa: E501
        """
        pass

    def test_chart_data_points_get_id(self):
        """Test case for chart_data_points_get_id

        DataPoints: Get by Id  # noqa: E501
        """
        pass

    def test_chart_plot_type_get(self):
        """Test case for chart_plot_type_get

        PlotType: List All Possible Types  # noqa: E501
        """
        pass

    def test_chart_plot_type_get_id(self):
        """Test case for chart_plot_type_get_id

        PlotType: Get by Id  # noqa: E501
        """
        pass

    def test_chart_row_col_get(self):
        """Test case for chart_row_col_get

        RowCol: List All Possible Types  # noqa: E501
        """
        pass

    def test_chart_row_col_get_id(self):
        """Test case for chart_row_col_get_id

        RowCol: Get by Id  # noqa: E501
        """
        pass

    def test_chart_row_collections_get_id(self):
        """Test case for chart_row_collections_get_id

        RowCollections: Get by Id  # noqa: E501
        """
        pass

    def test_chart_row_name_format_types_get(self):
        """Test case for chart_row_name_format_types_get

        RowNameFormatTypes: List All Possible Types  # noqa: E501
        """
        pass

    def test_chart_row_name_format_types_get_id(self):
        """Test case for chart_row_name_format_types_get_id

        RowNameFormatTypes: Get by Id  # noqa: E501
        """
        pass

    def test_chart_rows_get_id(self):
        """Test case for chart_rows_get_id

        Rows: Get by Id  # noqa: E501
        """
        pass

    def test_charts_charts_details_id(self):
        """Test case for charts_charts_details_id

        Charts: Retrieve Object Tree  # noqa: E501
        """
        pass

    def test_charts_charts_get_id(self):
        """Test case for charts_charts_get_id

        Charts: Get by Id  # noqa: E501
        """
        pass

    def test_documents_controller_documents_download_document_id(self):
        """Test case for documents_controller_documents_download_document_id

        Link to download a user's document. Can only be accessed by the users who owns the document  # noqa: E501
        """
        pass

    def test_documents_controller_documents_get_id(self):
        """Test case for documents_controller_documents_get_id

        Get document information by document id  # noqa: E501
        """
        pass

    def test_documents_controller_documents_post(self):
        """Test case for documents_controller_documents_post

        Upload a file into the docAPI, returns a document ids  # noqa: E501
        """
        pass

    def test_documents_document_type_get(self):
        """Test case for documents_document_type_get

        DocumentType: List All Possible Types  # noqa: E501
        """
        pass

    def test_documents_document_type_get_id(self):
        """Test case for documents_document_type_get_id

        DocumentType: Get by Id  # noqa: E501
        """
        pass

    def test_shared_color_transformation_attributes_get_id(self):
        """Test case for shared_color_transformation_attributes_get_id

        ColorTransformationAttributes: Get by Id  # noqa: E501
        """
        pass

    def test_shared_color_transformation_attributes_put_id(self):
        """Test case for shared_color_transformation_attributes_put_id

        ColorTransformationAttributes: Modify Values  # noqa: E501
        """
        pass

    def test_shared_color_transformations_get_id(self):
        """Test case for shared_color_transformations_get_id

        ColorTransformations: Get by Id  # noqa: E501
        """
        pass

    def test_shared_color_types_get(self):
        """Test case for shared_color_types_get

        ColorTypes: List All Possible Types  # noqa: E501
        """
        pass

    def test_shared_color_types_get_id(self):
        """Test case for shared_color_types_get_id

        ColorTypes: Get by Id  # noqa: E501
        """
        pass

    def test_shared_dash_types_get(self):
        """Test case for shared_dash_types_get

        DashTypes: List All Possible Types  # noqa: E501
        """
        pass

    def test_shared_dash_types_get_id(self):
        """Test case for shared_dash_types_get_id

        DashTypes: Get by Id  # noqa: E501
        """
        pass

    def test_shared_effect_attributes_get_id(self):
        """Test case for shared_effect_attributes_get_id

        EffectAttributes: Get by Id  # noqa: E501
        """
        pass

    def test_shared_effect_attributes_put_id(self):
        """Test case for shared_effect_attributes_put_id

        EffectAttributes: Modify Values  # noqa: E501
        """
        pass

    def test_shared_effect_types_get(self):
        """Test case for shared_effect_types_get

        EffectTypes: List All Possible Types  # noqa: E501
        """
        pass

    def test_shared_effect_types_get_id(self):
        """Test case for shared_effect_types_get_id

        EffectTypes: Get by Id  # noqa: E501
        """
        pass

    def test_shared_effects_get_id(self):
        """Test case for shared_effects_get_id

        Effects: Get by Id  # noqa: E501
        """
        pass

    def test_shared_fill_map_get_id(self):
        """Test case for shared_fill_map_get_id

        FillMap: Get by Id  # noqa: E501
        """
        pass

    def test_shared_fill_types_get(self):
        """Test case for shared_fill_types_get

        FillTypes: List All Possible Types  # noqa: E501
        """
        pass

    def test_shared_fill_types_get_id(self):
        """Test case for shared_fill_types_get_id

        FillTypes: Get by Id  # noqa: E501
        """
        pass

    def test_shared_gradient_fills_get_id(self):
        """Test case for shared_gradient_fills_get_id

        GradientFills: Get by Id  # noqa: E501
        """
        pass

    def test_shared_gradient_fills_put_id(self):
        """Test case for shared_gradient_fills_put_id

        GradientFills: Modify Values  # noqa: E501
        """
        pass

    def test_shared_gradient_stops_get_id(self):
        """Test case for shared_gradient_stops_get_id

        GradientStops: Get by Id  # noqa: E501
        """
        pass

    def test_shared_gradient_stops_put_id(self):
        """Test case for shared_gradient_stops_put_id

        GradientStops: Modify Values  # noqa: E501
        """
        pass

    def test_shared_image_fills_get_id(self):
        """Test case for shared_image_fills_get_id

        ImageFills: Get by Id  # noqa: E501
        """
        pass

    def test_shared_image_fills_put_id(self):
        """Test case for shared_image_fills_put_id

        ImageFills: Modify Values  # noqa: E501
        """
        pass

    def test_shared_line_end_sizes_get(self):
        """Test case for shared_line_end_sizes_get

        LineEndSizes: List All Possible Types  # noqa: E501
        """
        pass

    def test_shared_line_end_sizes_get_id(self):
        """Test case for shared_line_end_sizes_get_id

        LineEndSizes: Get by Id  # noqa: E501
        """
        pass

    def test_shared_line_end_types_get(self):
        """Test case for shared_line_end_types_get

        LineEndTypes: List All Possible Types  # noqa: E501
        """
        pass

    def test_shared_line_end_types_get_id(self):
        """Test case for shared_line_end_types_get_id

        LineEndTypes: Get by Id  # noqa: E501
        """
        pass

    def test_shared_lines_get_id(self):
        """Test case for shared_lines_get_id

        Lines: Get by Id  # noqa: E501
        """
        pass

    def test_shared_lines_put_id(self):
        """Test case for shared_lines_put_id

        Lines: Modify Values  # noqa: E501
        """
        pass

    def test_shared_paragraph_get_id(self):
        """Test case for shared_paragraph_get_id

        Paragraph: Get by Id  # noqa: E501
        """
        pass

    def test_shared_pictures_get_id(self):
        """Test case for shared_pictures_get_id

        Pictures: Get by Id  # noqa: E501
        """
        pass

    def test_shared_pictures_put_id(self):
        """Test case for shared_pictures_put_id

        Pictures: Modify Values  # noqa: E501
        """
        pass

    def test_shared_solid_fills_get_id(self):
        """Test case for shared_solid_fills_get_id

        SolidFills: Get by Id  # noqa: E501
        """
        pass

    def test_shared_solid_fills_put_id(self):
        """Test case for shared_solid_fills_put_id

        SolidFills: Modify Values  # noqa: E501
        """
        pass

    def test_shared_text_container_get_id(self):
        """Test case for shared_text_container_get_id

        TextContainer: Get by Id  # noqa: E501
        """
        pass

    def test_shared_text_get_id(self):
        """Test case for shared_text_get_id

        Text: Get by Id  # noqa: E501
        """
        pass

    def test_shared_text_put_id(self):
        """Test case for shared_text_put_id

        Text: Modify Values  # noqa: E501
        """
        pass

    def test_slides_color_maps_get_id(self):
        """Test case for slides_color_maps_get_id

        ColorMaps: Get by Id  # noqa: E501
        """
        pass

    def test_slides_graphic_types_get(self):
        """Test case for slides_graphic_types_get

        GraphicTypes: List All Possible Types  # noqa: E501
        """
        pass

    def test_slides_graphic_types_get_id(self):
        """Test case for slides_graphic_types_get_id

        GraphicTypes: Get by Id  # noqa: E501
        """
        pass

    def test_slides_graphics_get_id(self):
        """Test case for slides_graphics_get_id

        Graphics: Get by Id  # noqa: E501
        """
        pass

    def test_slides_group_element_types_get(self):
        """Test case for slides_group_element_types_get

        GroupElementTypes: List All Possible Types  # noqa: E501
        """
        pass

    def test_slides_group_element_types_get_id(self):
        """Test case for slides_group_element_types_get_id

        GroupElementTypes: Get by Id  # noqa: E501
        """
        pass

    def test_slides_group_elements_get_id(self):
        """Test case for slides_group_elements_get_id

        GroupElements: Get by Id  # noqa: E501
        """
        pass

    def test_slides_groups_get_id(self):
        """Test case for slides_groups_get_id

        Groups: Get by Id  # noqa: E501
        """
        pass

    def test_slides_shape_trees_get_id(self):
        """Test case for slides_shape_trees_get_id

        ShapeTrees: Get by Id  # noqa: E501
        """
        pass

    def test_slides_slide_masters_get_id(self):
        """Test case for slides_slide_masters_get_id

        SlideMasters: Get by Id  # noqa: E501
        """
        pass

    def test_slides_slides_details_id(self):
        """Test case for slides_slides_details_id

        Slides: Retrieve Object Tree  # noqa: E501
        """
        pass

    def test_slides_slides_get_id(self):
        """Test case for slides_slides_get_id

        Slides: Get by Id  # noqa: E501
        """
        pass

    def test_tables_borders_get_id(self):
        """Test case for tables_borders_get_id

        Borders: Get by Id  # noqa: E501
        """
        pass

    def test_tables_cells_get_id(self):
        """Test case for tables_cells_get_id

        Cells: Get by Id  # noqa: E501
        """
        pass

    def test_tables_columns_get_id(self):
        """Test case for tables_columns_get_id

        Columns: Get by Id  # noqa: E501
        """
        pass

    def test_tables_rows_get_id(self):
        """Test case for tables_rows_get_id

        Rows: Get by Id  # noqa: E501
        """
        pass

    def test_tables_tables_details_id(self):
        """Test case for tables_tables_details_id

        Tables: Retrieve Object Tree  # noqa: E501
        """
        pass

    def test_tables_tables_get_id(self):
        """Test case for tables_tables_get_id

        Tables: Get by Id  # noqa: E501
        """
        pass

    def test_theme_themes_details_id(self):
        """Test case for theme_themes_details_id

        Theme: Retrieve Object Tree  # noqa: E501
        """
        pass

    def test_theme_themes_get_id(self):
        """Test case for theme_themes_get_id

        Themes: Get by Id  # noqa: E501
        """
        pass

    def test_themes_background_fills_get_id(self):
        """Test case for themes_background_fills_get_id

        BackgroundFills: Get by Id  # noqa: E501
        """
        pass

    def test_themes_colors_get_id(self):
        """Test case for themes_colors_get_id

        Colors: Get by Id  # noqa: E501
        """
        pass

    def test_themes_custom_colors_get_id(self):
        """Test case for themes_custom_colors_get_id

        CustomColors: Get by Id  # noqa: E501
        """
        pass

    def test_themes_effect_map_get_id(self):
        """Test case for themes_effect_map_get_id

        EffectMap: Get by Id  # noqa: E501
        """
        pass

    def test_themes_fills_get_id(self):
        """Test case for themes_fills_get_id

        Fills: Get by Id  # noqa: E501
        """
        pass

    def test_themes_fonts_get_id(self):
        """Test case for themes_fonts_get_id

        Fonts: Get by Id  # noqa: E501
        """
        pass

    def test_themes_intensity_get(self):
        """Test case for themes_intensity_get

        Intensity: List All Possible Types  # noqa: E501
        """
        pass

    def test_themes_intensity_get_id(self):
        """Test case for themes_intensity_get_id

        Intensity: Get by Id  # noqa: E501
        """
        pass

    def test_themes_line_map_get_id(self):
        """Test case for themes_line_map_get_id

        LineMap: Get by Id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
